name: krocbox
description: "Balanced AMD Gaming & DevOps Workstation"
base-image: ghcr.io/ublue-os/bluefin
image-version: "stable"

modules:
  # RPM-Ostree packages with safe removal and branding tweaks
  - type: script
    scripts:
      - |
        #!/bin/bash
        set -e

        echo "Removing unwanted packages if they exist..."
        for pkg in gnome-initial-setup fedora-user-agent fedora-logos; do
          if rpm-ostree status --json | jq -r '.deployments[].basePackages[]' | grep -qx "$pkg"; then
            echo "Removing $pkg..."
            rpm-ostree override remove "$pkg"
          else
            echo "$pkg not installed; skipping..."
          fi
        done

        echo "Installing required packages..."
        rpm-ostree install \
          gnome-shell-extension-pop-shell \
          distrobox \
          tailscale \
          starship \
          flatseal \
          ufw \
          plymouth-theme-spinner

        echo "Replacing default GNOME login screen logo..."
        if [ -f /usr/share/pixmaps/krocbox-logo.png ]; then
          mkdir -p /usr/share/icons/hicolor/256x256/apps
          cp /usr/share/pixmaps/krocbox-logo.png /usr/share/icons/hicolor/256x256/apps/fedora-logo.png
        fi

        echo "Replacing Plymouth boot splash logo..."
        if [ -f /usr/share/pixmaps/krocbox-logo.png ]; then
          mkdir -p /usr/share/plymouth/themes/spinner
          cp /usr/share/pixmaps/krocbox-logo.png /usr/share/plymouth/themes/spinner/spinner.png
        fi

  # Script module for RPM Fusion and extra packages
  - type: script
    scripts:
      - |
        #!/bin/bash
        set -e

        echo "Enabling RPM Fusion Free & Nonfree repositories..."
        rpm-ostree install \
          https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
          https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

        echo "Installing RPM Fusion packages..."
        rpm-ostree install steam mangohud mesa-va-drivers-freeworld

  # Flatpaks
  - type: default-flatpaks
    configurations:
      - install:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - im.riot.Element
          - com.visualstudio.code
          - org.audacityteam.Audacity

  # Janitor / custom script
  - type: script
    scripts:
      - setup-krocbox-janitor.sh

  # Custom files (wallpaper and logos)
  - type: files
    files:
      - from: files/krocbox-wallpaper.png
        to: /usr/share/backgrounds/krocbox-wallpaper.png
      - from: files/krocbox-logo.png
        to: /usr/share/pixmaps/krocbox-logo.png
