name: krocbox
description: Balanced AMD Gaming & DevOps Workstation (Medium Hardened)
base-image: ghcr.io/ublue-os/mainline:latest

modules:
  - type: rpm-ostree
    remove:
      - gnome-initial-setup
      - fedora-user-agent
    install:
      - gnome-shell-extension-pop-shell
      - distrobox
      - steam
      - mesa-va-drivers-freeworld
      - mangohud
      - lact
      - tailscale
      - starship
      - flatseal
      - ufw

  - type: default-flatpaks
    install:
      - org.mozilla.firefox
      - com.discordapp.Discord
      - im.riot.Element
      - com.visualstudio.code
      - org.audacityteam.Audacity

  - type: script
    scripts:
      - setup-krocbox-janitor.sh
