# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: krocbox
description: "Balanced AMD Gaming & DevOps Workstation"

base-image: ghcr.io/ublue-os/bluefin
image-version: "stable"

modules:
  - type: rpm-ostree
    # Remove unneeded packages
    remove:
      - gnome-initial-setup
      - fedora-user-agent
      - fedora-logos

    # Install core packages
    install:
      - gnome-shell-extension-pop-shell
      - distrobox
      - steam
      - mangohud
      - lact
      - tailscale
      - starship
      - flatseal
      - ufw
      - plymouth-theme-spinner

    # Enable extra repos needed for some packages
    configurations:
      - type: script
        scripts:
          - |
            #!/bin/bash
            # Enable RPM Fusion Free and Nonfree
            rpm-ostree install \
              https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
              https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

            # Now install packages from RPM Fusion
            rpm-ostree install mesa-va-drivers-freeworld

  - type: default-flatpaks
    configurations:
      - install:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - im.riot.Element
          - com.visualstudio.code
          - org.audacityteam.Audacity

  - type: script
    scripts:
      - setup-krocbox-janitor.sh

  - type: files
    files:
      - from: files/krocbox-wallpaper.png
        to: /usr/share/backgrounds/krocbox-wallpaper.png
      - from: files/krocbox-logo.png
        to: /usr/share/pixmaps/krocbox-logo.png
