name: krocbox
description: Krocbox OS | Cloud Native Gaming & DevOps Workstation
base-image: ghcr.io/ublue-os/bazzite-dx
image-version: stable

modules:
  - type: os-release
    properties:
      NAME: krocbox
      ID: krocbox
      PRETTY_NAME: Krocbox OS
      DEFAULT_HOSTNAME: krocbox

  - type: rpm-ostree
    install:
      - tailscale
      - ufw
      - htop
      - fastfetch

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - com.visualstudio.code
          - org.gnome.World.PikaBackup
          - com.spotify.Client

  - type: script
    scripts:
      - branding.sh

  # Silent boot
  - type: kargs
    kargs:
      - quiet
      - splash

  # Boot splash
  - type: plymouth
    theme: krocbox
