# yaml-language-server: $schema=https://schema.blue-build.org
name: krocbox
description: Balanced AMD Gaming & DevOps Workstation
image-version: 1
base-image: ghcr.io/ublue-os/mainline:latest

modules:
  - type: rpm-ostree
    remove:
      - gnome-initial-setup
      - fedora-user-agent
      - fedora-logos
    install:
      - gnome-shell-extension-pop-shell
      - distrobox
      - steam
      - mesa-va-drivers-freeworld
      - mangohud
      - lact
      - tailscale
      - starship
      - flatseal
      - ufw
      - plymouth-theme-spinner

  - type: default-flatpaks
    configurations:
      - install:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - im.riot.Element
          - com.visualstudio.code
          - org.audacityteam.Audacity

  - type: script
    scripts:
      - setup-krocbox-janitor.sh

  - type: files
    files:
      - from: files/krocbox-wallpaper.png
        to: /usr/share/backgrounds/krocbox-wallpaper.png
      - from: files/krocbox-logo.png
        to: /usr/share/pixmaps/krocbox-logo.png
