# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: krocbox
description: "Balanced AMD Gaming & DevOps Workstation"

base-image: ghcr.io/ublue-os/bluefin
image-version: "stable"

modules:
  - type: rpm-ostree
    # Remove unneeded packages
    remove:
      - gnome-initial-setup
      - fedora-user-agent
      - fedora-logos

    # Install core packages from default repos
    install:
      - gnome-shell-extension-pop-shell
      - distrobox
      - steam
      - mangohud
      - tailscale
      - starship
      - flatseal
      - ufw
      - plymouth-theme-spinner

  - type: script
    # Custom script module for RPM Fusion + extra packages
    scripts:
      - |
        #!/bin/bash
        set -e

        echo "Enabling RPM Fusion Free & Nonfree repositories..."
        rpm-ostree install \
          https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
          https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

        echo "Installing mesa-va-drivers-freeworld from RPM Fusion..."
        rpm-ostree install mesa-va-drivers-freeworld

  - type: default-flatpaks
    configurations:
      - install:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - im.riot.Element
          - com.visualstudio.code
          - org.audacityteam.Audacity

  - type: script
    scripts:
      - setup-krocbox-janitor.sh

  - type: files
    files:
      - from: files/krocbox-wallpaper.png
        to: /usr/share/backgrounds/krocbox-wallpaper.png
      - from: files/krocbox-logo.png
        to: /usr/share/pixmaps/krocbox-logo.png
