name: krocbox
description: "Balanced AMD Gaming & DevOps Workstation (Medium Hardened)"
base-image: ghcr.io/ublue-os/mainline:latest
image-version: "stable"

modules:
  # Main setup: remove unwanted packages, install essentials, replace logos
  - type: script
    scripts:
      - files/scripts/krocbox-setup.sh

  # RPM Fusion & extra packages
  - type: script
    scripts:
      - files/scripts/rpmfusion-setup.sh

  # Flatpak apps
  - type: default-flatpaks
    configurations:
      - install:
          - org.mozilla.firefox
          - com.discordapp.Discord
          - im.riot.Element
          - com.visualstudio.code
          - org.audacityteam.Audacity

  # Auto-Janitor (weekly cleanup)
  - type: script
    scripts:
      - files/scripts/setup-krocbox-janitor.sh

  # Custom files: wallpaper and logo
  - type: files
    files:
      - from: files/krocbox-wallpaper.png
        to: /usr/share/backgrounds/krocbox-wallpaper.png
      - from: files/krocbox-logo.png
        to: /usr/share/pixmaps/krocbox-logo.png
